package pro.siberians.ws.stream.model;

import java.util.Date;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "contest-streamer-data")
public class ContestUserModel {

	public static String PK_PREFIX = "CONTEST_USER#";

	private String pk;
	private String sk;

	private Date createdAt;
	private Date updatedAt;

	// Primary key

	@DynamoDBHashKey public String getPk() { return pk; }
	@DynamoDBRangeKey public String getSk() { return sk; }

	public void setPk(String pk) { this.pk = pk; }
	public void setSk(String sk) { this.sk = sk; }

	// Working with contest GUID

	@DynamoDBIgnore
	public String getContestGuid() {
		return pk.replaceFirst("^" + PK_PREFIX, "");

	}

	public void setContestGuid(String contestGuid) {
		this.pk = PK_PREFIX + contestGuid;
	}

	// Working with user email

	@DynamoDBIgnore public String getUserEmail() { return sk; }

	public void setUserEmail(String userEmail) { this.sk = userEmail; }

	// Other attribute getters

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	public Date getCreatedAt() { return createdAt; };

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	public Date getUpdatedAt() { return updatedAt; }

	// Other attribute setters

	public void setCreatedAt(Date createdAt) { this.createdAt = createdAt; }
	public void setUpdatedAt(Date updatedAt) { this.updatedAt = updatedAt; }

}
