package pro.siberians.ws.stream.model;

import java.util.Date;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "contest-streamer-data")
public class ContestModel {

	public static String PK = "CONTEST";

	private String pk = PK;
	private String sk;

	private String name;
	private String status;

	private Date startAt;
	private Date finishAt;

	private Boolean awsInstCreated;
	private String awsInstType;
	private String awsInstId;

	private Boolean awsIpAllocated;
	private String awsIpAllocId;
	private String awsIpAllocAddr;

	private Boolean awsIpAssociated;
	private String awsIpAssocId;

	private Boolean awsDnsRecorded;
	private String awsDnsDomain;

	private String awsLastError;

	private String openViduSecret;

	private Date createdAt;
	private Date updatedAt;

	// Primary key

	@DynamoDBHashKey public String getPk() { return pk; }
	@DynamoDBRangeKey public String getSk() { return sk; }

	public void setPk(String pk) { this.pk = pk; }
	public void setSk(String sk) { this.sk = sk; }

	// Working with contest GUID

	@DynamoDBIgnore public String getGuid() { return sk; }

	public void setGuid(String guid) { this.sk = guid; }

	// Other attribute getters

	@DynamoDBAttribute public String getName() { return name; }
	@DynamoDBAttribute public String getStatus() { return status; }

	@DynamoDBAttribute public Date getStartAt() { return startAt; }
	@DynamoDBAttribute public Date getFinishAt() { return finishAt; }

	@DynamoDBAttribute public Boolean getAwsInstCreated() { return awsInstCreated; }
	@DynamoDBAttribute public String getAwsInstType() { return awsInstType; }
	@DynamoDBAttribute public String getAwsInstId() { return awsInstId; }

	@DynamoDBAttribute public Boolean getAwsIpAllocated() { return awsIpAllocated; }
	@DynamoDBAttribute public String getAwsIpAllocId() { return awsIpAllocId; }
	@DynamoDBAttribute public String getAwsIpAllocAddr() { return awsIpAllocAddr; }

	@DynamoDBAttribute public Boolean getAwsIpAssociated() { return awsIpAssociated; }
	@DynamoDBAttribute public String getAwsIpAssocId() { return awsIpAssocId; }

	@DynamoDBAttribute public Boolean getAwsDnsRecorded() { return awsDnsRecorded; }
	@DynamoDBAttribute public String getAwsDnsDomain() { return awsDnsDomain; }

	@DynamoDBAttribute public String getAwsLastError() { return awsLastError; }

	@DynamoDBAttribute public String getOpenViduSecret() { return openViduSecret; }

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	public Date getCreatedAt() { return createdAt; }

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	public Date getUpdatedAt() { return updatedAt; }

	// Other attribute setters

	public void setName(String name) { this.name = name; }
	public void setStatus(String status) { this.status = status; }

	public void setStartAt(Date startAt) { this.startAt = startAt; }
	public void setFinishAt(Date finishAt) { this.finishAt = finishAt; }

	public void setAwsInstCreated(Boolean awsInstCreated) { this.awsInstCreated = awsInstCreated; }
	public void setAwsInstType(String awsInstType) { this.awsInstType = awsInstType; }
	public void setAwsInstId(String awsInstId) { this.awsInstId = awsInstId; }

	public void setAwsIpAllocated(Boolean awsIpAllocated) { this.awsIpAllocated = awsIpAllocated; }
	public void setAwsIpAllocId(String awsIpAllocId) { this.awsIpAllocId = awsIpAllocId; }
	public void setAwsIpAllocAddr(String awsIpAllocAddr) { this.awsIpAllocAddr = awsIpAllocAddr; }

	public void setAwsIpAssociated(Boolean awsIpAssociated) { this.awsIpAssociated = awsIpAssociated; }
	public void setAwsIpAssocId(String awsIpAssocId) { this.awsIpAssocId = awsIpAssocId; }

	public void setAwsDnsRecorded(Boolean awsDnsRecorded) { this.awsDnsRecorded = awsDnsRecorded; }
	public void setAwsDnsDomain(String awsDnsDomain) { this.awsDnsDomain = awsDnsDomain; }

	public void setAwsLastError(String awsLastError) { this.awsLastError = awsLastError; }

	public void setOpenViduSecret(String openViduSecret) { this.openViduSecret = openViduSecret; }

	public void setCreatedAt(Date createdAt) { this.createdAt = createdAt; }
	public void setUpdatedAt(Date updatedAt) { this.updatedAt = updatedAt; }

}
