package pro.siberians.ws.stream.model;

import java.util.Date;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "contest-streamer-data")
public class UserContestModel {

	public static String PK_PREFIX = "USER_CONTEST#";

	private String pk;
	private String sk;

	private String contestName;
	private Date contestStartAt;
	private Date contestFinishAt;

	private Date createdAt;
	private Date updatedAt;

	// Primary key

	@DynamoDBHashKey public String getPk() { return pk; }
	@DynamoDBRangeKey public String getSk() { return sk; }

	public void setPk(String pk) { this.pk = pk; }
	public void setSk(String sk) { this.sk = sk; }

	// Working with user email

	@DynamoDBIgnore
	public String getUserEmail() {
		return pk.replaceFirst("^" + PK_PREFIX, "");
	}

	public void setUserEmail(String userEmail) {
		this.pk = PK_PREFIX + userEmail;
	}

	// Working with contest status and GUID

	@DynamoDBIgnore
	public String getContestStatus() {
		return sk.split("#")[0];
	}

	@DynamoDBIgnore
	public String getContestGuid() {
		return sk.split("#")[1];
	}

	public void setContestStatusAndGuid(String contestStatus, String contestGuid) {
		this.sk = contestStatus + "#" + contestGuid;
	}

	// Other attribute getters

	@DynamoDBAttribute public String getContestName() { return contestName; };
	@DynamoDBAttribute public Date getContestStartAt() { return contestStartAt; };
	@DynamoDBAttribute public Date getContestFinishAt() { return contestFinishAt; };

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	public Date getCreatedAt() { return createdAt; };

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	public Date getUpdatedAt() { return updatedAt; }

	// Other attribute setters

	public void setContestName(String contestName) { this.contestName = contestName; };
	public void setContestStartAt(Date contestStartAt) { this.contestStartAt = contestStartAt; };
	public void setContestFinishAt(Date contestFinishAt) { this.contestFinishAt = contestFinishAt; };

	public void setCreatedAt(Date createdAt) { this.createdAt = createdAt; }
	public void setUpdatedAt(Date updatedAt) { this.updatedAt = updatedAt; }

}
